### ISSUE TITLE
第166期 not_null <int> 是不是应该是not_null <int*>

### ISSUE THREAD

**Issue by Nevermore1994** [wanghenshui/cppweeklynews#125]
https://github.com/wanghenshui/cppweeklynews/releases/tag/v1.6.6#:~:text=void%20consume(not_null%3Cint%3E%20ptr)%3B%20//std%3A%3Aunique_ptr%3Cint%3E%20%26%26%20%E4%B9%9F%E5%8F%AF%E4%BB%A5

**Comment by wanghenshui** [comment]
你说的对，这里写错了。我下一期标注一下
