### ISSUE TITLE
rss 似乎无效

### ISSUE THREAD

**Issue by chinyajie** [wanghenshui/cppweeklynews#3]
提供的 rss 链接失效了~

edit by wanghenshui:
可以使用https://github.com/wanghenshui/cppweeklynews/releases.atom 来接收最新信息，会主动更新
多谢[suxb201](https://github.com/suxb201)

**Comment by wanghenshui** [comment]
我研究一下

**Comment by westfly** [comment]
[rss](https://github.com/ruanyf/weekly/issues/2132) 似乎可以通过github的action自动生成
![image](https://user-images.githubusercontent.com/1453169/148483160-62be1880-970f-4162-be23-eb4434e52e3a.png)

**Comment by EastLord** [comment]
我用的Reeder
![image](https://user-images.githubusercontent.com/14818667/148495664-652e3ca4-1587-4fc8-97b5-110a711b2b11.png)

**Comment by wanghenshui** [comment]
> [rss](https://github.com/ruanyf/weekly/issues/2132) 似乎可以通过github的action自动生成 ![image](https://user-images.githubusercontent.com/1453169/148483160-62be1880-970f-4162-be23-eb4434e52e3a.png)

我研究下

**Comment by wanghenshui** [comment]
> > [rss](https://github.com/ruanyf/weekly/issues/2132) 似乎可以通过github的action自动生成 ![image](https://user-images.githubusercontent.com/1453169/148483160-62be1880-970f-4162-be23-eb4434e52e3a.png)
> 
> 我研究下


这个是在已有rss的基础上做广播。我目前已有的rss就不好使。

**Comment by suxb201** [comment]
每一期发一个 Release，GitHub 自带 Release 的 RSS
```
/* Repo releases */

https://github.com/:owner/:repo/releases.atom
```

**Comment by wanghenshui** [comment]
> 每一期发一个 Release，GitHub 自带 Release 的 RSS
> 
> ```
> /* Repo releases */
> 
> https://github.com/:owner/:repo/releases.atom
> ```

我下一期打tag

**Comment by wanghenshui** [comment]
> 每一期发一个 Release，GitHub 自带 Release 的 RSS
> 
> ```
> /* Repo releases */
> 
> https://github.com/:owner/:repo/releases.atom
> ```

https://github.com/wanghenshui/cppweeklynews/releases.atom 实际上一个包，看不到东西的

**Comment by suxb201** [comment]
@wanghenshui 你要写东西的，比如这个：https://github.com/redis/redis-py/releases.atom

**Comment by wanghenshui** [comment]
> @wanghenshui 你要写东西的，比如这个：https://github.com/redis/redis-py/releases.atom

我懂你的意思了，就是把内容放在release上发一遍

**Comment by AmosChenYQ** [comment]
最新一期118并没有在rss展示出来 https://github.com/wanghenshui/cppweeklynews/releases.atom

**Comment by wanghenshui** [comment]
> 最新一期118并没有在rss展示出来 https://github.com/wanghenshui/cppweeklynews/releases.atom

118忘发了
