### ISSUE TITLE
recommend post

### ISSUE THREAD

**Issue by c8ef** [wanghenshui/cppweeklynews#6]
[STL/STL](https://github.com/StephanTLavavej/STL)

MSVC STL组老大自己实现的刚进c++23的`import std;`。

**Comment by wanghenshui** [comment]
> [STL/STL](https://github.com/StephanTLavavej/STL)
> 
> MSVC STL组老大自己实现的刚进c++23的`import std;`。

@c8ef 好的。我放到下一期
