### ISSUE TITLE
第 126 期的编译期动态分配代码示例

### ISSUE THREAD

**Issue by fanenr** [wanghenshui/cppweeklynews#68]
# 位置

https://github.com/wanghenshui/cppweeklynews/blob/dev/posts/126.md#c20-dynamic-allocations-at-compile-time

# 问题

我看了一下原文，原文是最后将 Calc 标识为 constexpr，然后用 as_constant 函数强制这个 constexpr 函数在编译期计算。

您的原文中，将 Calc 函数标识为 consteval，后面加不加 as_constant 都会强制编译期计算。而且，res 本身是一个 run-time 变量，再作为参数调用 Calc 是百分百失败的。

我猜测是您笔误，将 Calc 函数标记错了？

**Comment by wanghenshui** [comment]
你说的对，抄错了
