### ISSUE TITLE
RSS链接订阅不全，老是跳期

### ISSUE THREAD

**Issue by gpncarl** [wanghenshui/cppweeklynews#92]
![Screenshot_40c1bcec-c74b-4b56-bb99-3c47fdc6a6dc](https://github.com/wanghenshui/cppweeklynews/assets/38633718/2899e4ab-b4c5-44b6-99fc-3d472b789efe)

**Comment by wanghenshui** [comment]
我的问题，我有时候就忘了

**Comment by wanghenshui** [comment]
145到147我补上了，其他的我看着补吧

**Comment by L-Super** [comment]
rss 停留在185期，未更新
